import html
import re
from datetime import datetime
from pathlib import Path

def get_folder():
    while True:
        target_folder = Path(input("[INPUT] Enter parent folder path: ").strip())
        if target_folder.is_dir():
            return target_folder
        print(f"[ERROR] Invalid path: '{target_folder}'")

def get_filename():
    while True:
        filename = clean_input(input("[INPUT] Enter filename: ").strip())
        if filename:
            return filename
        print("[ERROR] Filename cannot be empty.")

def clean_input(input_str):
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1F]', '_', input_str)
    cleaned = cleaned.strip()

    if not cleaned:
        print("[!!!!!] Invalid or empty filename detected. Using default name: 'hdml-output'")
        cleaned = "hdml-output"

    return cleaned

def find_images(target_folder):
    IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.gif', '.webp'}
    return [p for p in Path(target_folder).rglob("*") if p.suffix.lower() in IMAGE_EXTS]

def generate_html(filename, filecount, image_paths):
    header = f"""<!DOCTYPE HTML>
<!-- Created: {datetime.now().strftime("%B %d, %Y %H:%M:%S")}. Images included: {filecount} -->
<!-- Generated by hdml | https://github.com/spacegears/hdml -->
<html>
<head>
<title>{filename}</title>
<style>
body {{ background: #171717; }}
img {{ width: 100%; grid-area: 1 / 1 / 2 / 2; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); grid-gap: 1rem; }}
.item {{ background: black; padding: 0.2rem; display: grid; place-items: center; }}
.item::before {{ content: ""; display: block; padding-bottom: 100%; grid-area: 1 / 1 / 2 / 2; }}
</style>
</head>
<body>
<div class="grid">
"""
    items = '\n'.join(f'<div class="item"><img src="{html.escape(str(img))}" title="{html.escape(img.stem)}"></div>' for img in image_paths)
    footer = "\n</div>\n</body>\n</html>"
    return header + items + footer

def save_file(html_content, output_path):
    with open(output_path, 'w', encoding='utf-8') as file:
        file.write(html_content)

def main():
    print("[>>>>>] hdml by spacegears")
    target_folder = get_folder()
    filename = get_filename()
    filecreated = datetime.now().strftime("%Y%m%d")

    image_paths = find_images(target_folder)
    if not image_paths:
        print("[ERROR] No images found in folder.")
        return

    print("[>>>>>] Generating file...")

    image_paths.sort()
    filecount = len(image_paths)

    html_content = generate_html(filename, filecount, image_paths)
    script_directory = Path(__file__).resolve().parent
    output_path = script_directory / f"{filename}-{filecreated}.html"

    try:
        save_file(html_content, output_path)
        
        print("----------------------------------------")
        print(f"[>>>>>] {filename}.html was successfully generated.")
        print(f"[>>>>>] file://{output_path}")
        print(f"[>>>>>] Images included: {filecount}")
        
    except (IOError, OSError) as e:
        print(f"[ERROR] Could not save file: {e}")
    return

if __name__ == "__main__":
    main()